blank_issues_enabled: true
contact_links:
  - name: User Documentation
    url: https://vtt.red/ose
    about: "Learn how to get started with Old-School Essentials on Foundry VTT."
  - name: VTT Red Commercial Content Discord
    url: https://discord.gg/vWDJqCF24z
    about: "Ask a question in our help channels."
