name: Enhancement Request
description: Request a new feature or improvement to the current functionality.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request!
  - type: textarea
    id: new-behaviour
    attributes:
      label: New Feature or Changed Behaviour
      description: Describe your proposed enhancement in detail, and provide examples.
      placeholder: |
        Example: Create an additional map from the existing map image with a sepia paper texture to make it look more like an old treasure map.
    validations:
      required: true
  - type: textarea
    id: explanation-of-change
    attributes:
      label: Why?
      description: "Would this improve/shorten a player's workflow? Would this be more intuitive? Would it just look cool? Explain with details and examples."
      placeholder: |
        Players will be able to get more immersed during play. A little color and texture will add a lot to the overall feeling of fantasy adventure.
  - type: dropdown
    id: package-id
    attributes:
      label: Which package?
      description: Select the Necrotic Gnome product with this issue.
      options:
        - Advanced Fantasy
        - Halls of the Blood King
        - Holy Mountain Shaker
        - The Hole in the Oak
        - The Incandescent Grottoes
        - The Isle of the Plangent Mage
        - Winter's Daughter
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vttred/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true

